# Generated by Django 3.2.6 on 2021-08-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=264)),
                ('phone_number', models.IntegerField(max_length=10, unique=True)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
